version: '3.8'

services:
  jupyter:
    image: spark:latest
    container_name: spark-jupyter
    ports:
      - "8888:8888"
      - "4041:4041"
      - "4040:4040"
      - "18080:18080"
    volumes:
      - ./notebooks:/home/sparkuser/app
      - ./notebooks/event_logs:/home/spark/event_logs
    command: jupyter
    restart: unless-stopped

  spark-shell:
    image: spark:latest
    container_name: spark-shell
    ports:
      - "8888:8888"
      - "4041:4041"
      - "4040:4040"
      - "18080:18080"
    volumes:
      - ./notebooks:/home/sparkuser/app
      - ./notebooks/event_logs:/home/spark/event_logs
    command: spark-shell
    restart: unless-stopped

  pyspark:
    image: spark:latest
    container_name: pyspark
    ports:
      - "8888:8888"
      - "4041:4041"
      - "4040:4040"
      - "18080:18080"
    volumes:
      - ./notebooks:/home/sparkuser/app
      - ./notebooks/event_logs:/home/spark/event_logs
    command: pyspark
    restart: unless-stopped
